### PR TITLE
Fix chatMessage save

### PR DESCRIPTION
**Pull request by shubhsherl**
There were places where `CachedChatMessage.save` were not called after any change in chatMessage, which results in delay in updating of messages.

### CODE REVIEW

**Comment by Shailesh351** [comment]
@shubhsherl @ear-dev This solution works, it calls save method after every insert, update or remove using callback.

But In stead of adding callback every time we insert, update or remove. We can directly observe changes on mongo collection using cursors.
 
Add 
```
const cursor = ChatMessage.find({});

const observer = cursor.observe({
	changed() {
		CachedChatMessage.save();
	},
});
```
in https://github.com/WideChat/Rocket.Chat/blob/b131d9b7a7723d6c058cab344d748aa0174d0ac1/app/models/client/models/ChatMessage.js

So this will be only one file change. Can you test it at your end? Let me know your thoughts.
Thanks 😄
 
https://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges

**Comment by ear-dev** [comment]
Thanks @Shailesh351 

@shubhsherl What do you think?  Sounds like an elegant solution?

**Comment by shubhsherl** [comment]
@ear-dev  yeah, that's a more excellent way to do that. :smiley: 
Thanks @Shailesh351 
I'll update the PR

**Comment by shubhsherl** [comment]
Hi @Shailesh351 this method is not working in offline mode. Can you check once?

**Comment by shubhsherl** [comment]
I am closing this PR, in favour of a new PR.

**Pull request closed without merging**
