### PR TITLE
Initial Push Notification Message UI

### LINKED ISSUE #281: Push Notification Message Rendering in Viasat Chat Client

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/281
- [x] Title
- [x] Description
- [x] Icon
- [x] Timestamp
- [x] Action Buttons
- [x] Expand Collaps
<del> Format timestamp to make it similar to Android Notification </del>
- [x] Move styles to css file after UI styling is complete (For fast development I'm currently using inline styling)

localhost_3000_channel_general(Pixel 2 XL)

### CODE REVIEW

**Comment by Shailesh351** [comment]
@kb0304 @ear-dev update on this.

you can try this with different values by setting session variable. Use following command for testing on console.
```
Session.set("pushMessage",
{
	title: 'New Song on Youtube',
	options:
	{
		body: 'Nihil et maiores autem porro itaque modi. Est velit illum commodi consectetur voluptatibus impedit modi. Aspernatur cupiditate atque aut explicabo cum. Minus soluta ut et dolorem soluta. Tempore veritatis rerum inventore molestias est illum dolores.',
		icon: 'https://awsmp-logos.s3.amazonaws.com/dcb2092b-ef39-40bd-bc7c-f2394fa75ba7/16a827701bdfc7ae7ddf389f61507024.png',
		timestamp: new Date().getTime(),
		actions: [
		{
			action: 'yes',
			title: 'Watch Later',
			icon: 'https://image.flaticon.com/icons/svg/60/60731.svg',
		},
		{
			action: 'no',
			title: 'Discard',
			icon: 'https://image.flaticon.com/icons/svg/1828/1828778.svg',
		}, ],
	},
});
```

localhost_3000_channel_general(Pixel 2 XL) (2)

**Comment by Shailesh351** [comment]
@ear-dev @kb0304 For the date time format, currently it is same as in the sidebar item (HH:MM AM/PM / yesterday, date) etc.

In the android notification it is like (1m 1h 1d 1w) like this.

So in our case which format we want?

**Comment by Shailesh351** [comment]
New Update on Expand/Collapse functionality

Screen-Recording-2020-06-09-at-7

**Comment by ear-dev** [comment]
@kb0304 should this PR be against develop_pwa, or maybe against develop_push?  What do you think?

**Comment by ear-dev** [comment]
@kb0304 can you review this please and if it looks good go ahead and merge it when you are ready?

**Review by kb0304 — APPROVED** [review]

**Pull request merged**
