### PR TITLE
fix message action menu for touch

### LINKED ISSUE #163: Adding reactions, links in the message, thread msgs, etc. should not open the message action menu.

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #163

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl can you describe more, or send images, about what the issue here is that is being fixed?  I'm not sure I understand it, and have not been able to reproduce anything similar.  Thanks.

**Comment by shubhsherl** [comment]
@ear-dev it's on mobile device, when you click on some link within message or the user-image within message, currently it pop-ups the action menu too.
This PR solves that. 
If it's not clear, I'll upload a gif to show the bug.

**Comment by shubhsherl** [comment]
s

**Comment by ear-dev** [comment]
looks good.  Thanks!

**Pull request merged**
