### PR TITLE
[NEW] Refactor messagebox for mobile devices

### PR DESCRIPTION
**Pull request by bhardwajaditya**
## Proposed changes (including videos or screenshots)

image

image

image

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya I'm testing this on localhost, using dev tools in mobile view and it looks great....  but after I send a few messages it gets stuck; I can send a new message, but it does not appear in the window. 

I can see some errors in the console:

image

**Comment by ear-dev** [comment]
@bhardwajaditya Nico added an emoji flow to the figma.  I think it's a little different than what we currently have.  Can you take a look please?  Should we make a new story and PR for that, or just tack it onto this PR?

Thanks.

image

**Comment by bhardwajaditya** [comment]
@ear-dev for the emoji designs, I think it will be better to make a separate PR for that. I will look into the message sending issue

**Comment by ear-dev** [comment]
@bhardwajaditya can you remind me please where we are with the '+' button?  Are you waiting on Nico to show designs that do not include the gallery preview?

**Comment by ear-dev** [comment]
@bhardwajaditya FYI - Nico has added a view in the figma that shows the '+' button without the gallery preview.

**Review by ear-dev — APPROVED** [review]
@bhardwajaditya this looks good.  Can I merge this?

**Pull request merged**
