### PR TITLE
[NEW] Livechat setting to configure chat already closed message

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Issue Link - https://github.com/WideChat/Rocket.Chat/issues/1029

Livechat PR - https://github.com/WideChat/Rocket.Chat.Livechat/pull/118

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya I did manage to figure out how to use local store to keep the composer open.  My test worked, except I am not getting the configured message.  Instead I get a red banner that says "room-closed".....  any ideas why the configured message is not showing up?

image

**Comment by bhardwajaditya** [comment]
@ear-dev duplicate this tab and try sending a message there, it will block it and display the configured error message

**Comment by ear-dev** [comment]
> @ear-dev duplicate this tab and try sending a message there, it will block it and display the configured error message

I can try that, but shouldn't this work in the original tab?  Not sure I get it.  

@bhardwajaditya actually, when I duplicated the tab and typed into the open composer, it actually started a new room.  It did not block or display the configured message.

**Comment by bhardwajaditya** [comment]
@ear-dev In the original tab the room id is still present in the store data, which does not trigger the new room creation trigger. So sending a message to that room returns this error. Room data does not persist across tabs so new tab have composer disabled with no room attached to it, the scenario we are facing in prod where this message is triggering new room creation.

When a user opens a new chat, Livechat config URL is called it returns the config data and the room details attached with the visitor token. The problem in prod is that when user revisits the page, the config is called and no room is found but the client state is displayed as it is from cache with composer disabled.

This is the reason why duplicating the tab is kind of a tacky replica of the issue, no room attached composer disabled, no initial trigger fired. In this case with initial message new room should get created, which won't be the case post this change

**Review by ear-dev — APPROVED** [review]
Thanks!

**Pull request merged**
