### PR TITLE
Fix First Time Caching Libs in PWA

### LINKED ISSUE #332: PWA always loading in mobile offline mode. Only sometime it is working

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/332

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 @kb0304 Maybe I'm confused about something......  I'm testing this PR on an android emulator.  When I close the PWA, turn on airplane mode, and re-open the PWA, I'm getting an offline message and the PWA does not open at all.  I've installed the PWA using the "add to homescreen" option in the chrome hamburger menu.  Am I misunderstanding something?  I thought that we would be able to work offline. 

image

**Comment by Shailesh351** [comment]
@ear-dev In the emulator it doesn't work in offline mode. You can test on browser using dev tools.

1) Open pwa in incognito tab(so that is doesn't load from memory or service worker. To start fresh session).
2) In the network tab change internet connection to offline
3) Reload page. It should load from service worker in offline mode after this PR fix.

Without this PR it was not loading from service worker on first time loading. Let me know If you have any query on testing this fix.

**Review by ear-dev — APPROVED** [review]
nice!  Thanks for the info on how to test.

**Comment by ear-dev** [comment]
@Shailesh351 should this one also be ported to our upstream PRs, and the demo server?

**Comment by Shailesh351** [comment]
> @Shailesh351 should this one also be ported to our upstream PRs, and the demo server?

Yes @ear-dev I have created PR for our upstream demo. And Shubham is including this changes in one of upstream service worker PR. Thanks 🙂

**Pull request merged**
