### PR TITLE
[Upstream Catchup] Merge RC:master to develop_pwa

### PR DESCRIPTION
**Pull request by ear-dev**
Weekly Catchup PR to merge RC:master in develop_pwa.

### CODE REVIEW

**Comment by bhardwajaditya** [comment]
@ear-dev how do we want to go with these PRs, merge them one by one or push all the changes to the last one?

**Comment by ear-dev** [comment]
> @ear-dev how do we want to go with these PRs, merge them one by one or push all the changes to the last one?

yeah, I think that's the way to go.

**Comment by bhardwajaditya** [comment]
@ear-dev which one option 1 or 2?

**Comment by ear-dev** [comment]
> @ear-dev which one option 1 or 2?

Sorry......  "push all the changes to the last one".....  that way we make only one catchup commit to our develop_pwa branch...  thanks.

**Pull request closed without merging**
