### PR TITLE
[NEW] Display commit hash for RC Apps

### LINKED ISSUE #740: Show commit hash for each App (Dialoglow and Salesforce)
If we could easily view the commit hash in the UI that would be nice.

### PR DESCRIPTION
**Pull request by itzzritik**
# Display Commit Hash for RC Apps:
- Shows commit hash of head of the RC App
- Ability to copy the full commit hash

PR for the compiler: [Link](https://github.com/WideChat/Rocket.Chat.Apps-compiler/pull/10)

## Screenshots

image
untitled

### CODE REVIEW

**Comment by ear-dev** [comment]
@ItzzRitik this PR has 62 files changed....  is that correct?

**Comment by itzzritik** [comment]
@ear-dev Most of the files are just language files,
I've fixed the incorrect order.

But I can revert it back if you say so.

**Comment by itzzritik** [comment]
Also I'm not sure what's the issue with PR Title,
It's saying Malformed Title

**Comment by ear-dev** [comment]
Why are there Invitation_HTML changes in language files included in this PR?

**Comment by ear-dev** [comment]
OH, the malformed title has to do with a new convention Rocketchat implemented.  The title has to start with some [QUALIFIER-HERE]

If you start a new, dummy PR, you can read in the default description field what your options are.

**Comment by itzzritik** [comment]
@ear-dev it's just the order of those entries, and I ran a script which did all the order fixing for me.

I think, I'll revert it back

**Comment by chadgoss** [comment]
tested and verified

**Pull request merged**
