### PR TITLE
[FIX] Cypress Tests Post-Catchup Fix

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
For issue: https://github.com/WideChat/Rocket.Chat/issues/1221

## Proposed changes (including videos or screenshots)
Added functionality that closes the subscription warning modal to allow the correct testing of elements.

### CODE REVIEW

**Comment by Shailesh351** [comment]
@AlexanderKanakis `E2E Test UI` is disabled in https://github.com/WideChat/Rocket.Chat/blob/cypress_test_post_catchup_fix/.github/workflows/build_and_test.yml#L247...L270 So it is not running any cypress tests in the CI. Can you please check?

@AlexanderKanakis When I tested locally still most of the tests are failing. i.e. `tests/cypress/integration/05-channel-creation.spec.js` still fails even after adding `modal.close()`. Was it success for you?

**Comment by bhardwajaditya** [comment]
@AlexanderKanakis the Push_enable setting is by default set to true for new servers, but if we set it to false we won't need to handle the modal since it won't be displayed in the first place. The setting is given below.

https://github.com/WideChat/Rocket.Chat/blob/develop_pwa/app/lib/server/startup/settings.ts#L1424

**Comment by ear-dev** [comment]
@AlexanderKanakis please turn off our notifications by default in the settings file, as described by adityas comment above.  Then look at your cypress tests and work from there please.  thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis please disable any of the offline tests that may be blocking completion of this story.  Those features will soon be depricated, and I don't think we need to spend more time on the tests.

**Comment by Shailesh351** [comment]
@AlexanderKanakis `E2E Test UI` is disabled in https://github.com/WideChat/Rocket.Chat/blob/cypress_test_post_catchup_fix/.github/workflows/build_and_test.yml#L247...L270 So it is not running any cypress tests in the CI. Can you please check?

**Comment by Shailesh351** [comment]
@AlexanderKanakis Can you check the build failure, please? Thanks...

**Review by Shailesh351 — APPROVED** [review]
@ear-dev @AlexanderKanakis  PR Looks good to me. This PR skips some tests that are for PWA(offline/ home page etc). After @bhardwajaditya is done with removing PWA changes we should also these tests as well. Or may be @bhardwajaditya will remove those in his PR?

**Pull request merged**
