### PR TITLE
Use tabBar for message search in Room

### LINKED ISSUE #290: System-Level Back button shows "No channel with name ... was found"
Steps to Reproduce:
1. Open any room.
2. Press Searchbar in room header
3. Press system level back button
4. Open the room again

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #290 
Initially, we were user RocketSearch template within room.html by checking a Session var(`openSearchPage`). Because of which other parts of chatroom were not available in DOM when the user presses the system-level back button. And hence the issue:290.
This PR implements the Search in tabBar(similar to what we are using to display UserInfo/Members page).

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you test and review this one please?  Thanks!

**Comment by Shailesh351** [comment]
Will do @ear-dev 👍

**Comment by Shailesh351** [comment]
@shubhsherl This is not looking good as UI, showing extra blank space.

You can add this line `Session.set('openSearchPage', false);` in `menu.js` file at

```
this.on('open', ignore(() => {
	// WIDECHAT close main content
	this.mainContent.css('transform', 'translate3d( 100%, 0 , 0)');
	FlowRouter.withReplaceState(function() {
		FlowRouter.go('/home');
	});
	Session.set('openSearchPage', false);
}));
```

This will fix this issue.

**Comment by shubhsherl** [comment]
@Shailesh351 This seems to be an easy solution. Thanks.

**Comment by shubhsherl** [comment]
Closing in favour of #299

**Pull request closed without merging**
