### PR TITLE
[Upstream catchup] Merge RC:master to WD:develop_pwa

### LINKED ISSUE #321: upstream catchup into develop_pwa
we are still not able to see the games available in the marketplace on our server.  they suggested that maybe another upstream catchup will help.  If not we will have to continue to debug

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #321

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl or @Shailesh351 can you take a look at these conflicting files please?  I just merged a PR from Shailesh that had a migration with it, which I think must have caused the conflicts.  Thanks.

**Comment by ear-dev** [comment]
@shubhsherl Can you resolve these files next please?  Once we have this catchup with RC we will update all our branches and post on the dev server.  @Shailesh351 do you mind building this and testing it out please?  We have a history of losing some of our PWA changes during these catchup merges and it would be great if we can catch them now.  Thanks!

**Comment by shubhsherl** [comment]
@Shailesh351 PR is updated with latest RC:master.

**Comment by Shailesh351** [comment]
Thanks @shubhsherl I will test at my end.

**Comment by Shailesh351** [comment]
@shubhsherl 
- [ ] In the admin section it is showing hamburger icon instead of back button. And on clicking it is going to home screen(Chats). So user is not able to explore all admin settings.
- [ ] Directory Icon is not visible. So it is occupying blank space. @ear-dev We don't have directory option in dev server. Is it intentional?
- [ ] Redundant View Mode setting. View Mode option is twice available. Screenshot below. I think similar is there in dev server as well so need to fix it there. I will create issue.

Screenshot 2020-07-14 at 11 49 13 AM

Screenshot 2020-07-14 at 11 53 01 AM

Screenshot





This one I found till now. Will add in the list if I find any more issue.

**Comment by shubhsherl** [comment]
@Shailesh351 Thanks for the review, I've updated the required changes.

**Comment by ear-dev** [comment]
@Shailesh351 Thanks for taking a look!  Are you still checking things out, or do you think you're done?  

Yes - we have disabled the directory on purpose in our servers.  Perhaps we need a better way to track our Viasat specific changes so we don't go through this after every catchup?  Maybe we should at least make comments in the code when we know we are making Viasat specific changes?  Any other ideas?

**Comment by Shailesh351** [comment]
@shubhsherl @ear-dev Yes I'm checking again with shubham's fixes. Thanks @shubhsherl.

- [ ] We need to change hamburger icon to back arrow.  https://github.com/WideChat/Rocket.Chat/pull/308/files
- [ ] In the mobile, view mode option should no be there. You can add this changes https://github.com/RocketChat/Rocket.Chat/pull/17375/files#diff-cf98640c29a1cc07f5e21ffa46080022R38.
- [ ] Status icon in DM is not vertically aligned. You can add this changes https://github.com/WideChat/Rocket.Chat/pull/308/files

Will update if find any other :+1:

Thanks 😄

**Comment by Shailesh351** [comment]
DB Migration added in https://github.com/WideChat/Rocket.Chat/pull/324/files is not present now. It was for fixing adding missing lastMessage timestamp. We should test this one after deployment on dev server. Let's see if we are facing same issue after catch or not. If issue still persist. we can add migration.

**Comment by ear-dev** [comment]
@Shailesh351 It seems to me that db migrations we add can be a problem when we sync?  What's the best way to handle that?

**Comment by shubhsherl** [comment]
@Shailesh351 Thanks for the review, hamburger fits there for the admin page Since it first opens info page(not the admin side-nav). Hamburger is like a menu icon. Back button indicate to move backwards, i.e. Room list view. 
@ear-dev thoughts?

I'll fix others. 

For migration, the bug was from upstream, right? They haven't fixed it in upstream? Should I add it in existing v190, since adding another file will create inconsistency in version from upstream.

**Comment by Shailesh351** [comment]
> @Shailesh351 It seems to me that db migrations we add can be a problem when we sync? What's the best way to handle that?

For that, we should avoid db migration in our client in the first place. Because if we add migration and same is deployed on server, we could miss migration version with same number from upstream. 

We should have other way of running migration, which doesn't interfere with upstream migration. Kind of manual migration.

**Comment by Shailesh351** [comment]
> @Shailesh351 Thanks for the review, hamburger fits there for the admin page Since it first opens info page(not the admin side-nav). Hamburger is like a menu icon. Back button indicate to move backwards, i.e. Room list view.

Agree with you @shubhsherl. Thanks for the inputs. In that case we should also update the same in upstream demo branch and Upstream PRs as well.

**Comment by ear-dev** [comment]
> > @Shailesh351 It seems to me that db migrations we add can be a problem when we sync? What's the best way to handle that?
> 
> For that, we should avoid db migration in our client in the first place. Because if we add migration and same is deployed on server, we could miss migration version with same number from upstream.
> 
> We should have other way of running migration, which doesn't interfere with upstream migration. Kind of manual migration.

This catchup merge had a migration conflict, is that right?  What strategy have we used to resolve?  How would a 'manual' migration work?  And haven't we added migrations in the past, or is this the first migration conflict we've seen?

**Review by Shailesh351 — APPROVED** [review]
Looks good to me. Didn't notice any issue while local testing.

**Pull request merged**
