### PR TITLE
Push notifications subscription and storage

### LINKED ISSUE #250: Create method to save push notification subscription document on server

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes #250 

This includes:

- Subscription to push service on client
- Model creation for storing subscriptions
- Method to handle storage of push subscriptions

### CODE REVIEW

**Comment by kb0304** [comment]
Dynamically generate manifest.json

**Comment by bhardwajaditya** [comment]
> Dynamically generate manifest.json

I will include this part in separate PR since it requires some other changes.

**Comment by bhardwajaditya** [comment]
@shubhsherl do you have any idea on this test failure?

**Comment by shubhsherl** [comment]
@bhardwajaditya This is a known [issue](https://github.com/cypress-io/cypress/issues/2634) but is resolved in cypress. I encountered this in one of the Upstream PRs. But when I updated the PR(w/o changing anything related to cypress test, just a merge conflict). The test completed successfully.

**Comment by bhardwajaditya** [comment]
@shubhsherl yeah it worked now without any change addressing this issue.

**Pull request closed without merging**
