### PR TITLE
Add a Switch for friendlyUI in livechat

### LINKED ISSUE #696: [UI] Chat bubbles in the livechat widget

### PR DESCRIPTION
**Pull request by itzzritik**
This PR contains the following changes:
1. A Switch to Enable/Disable FriendlyUI in Livechat Widget
2. A Switch to Enable/Disable Avatars in Livechat Widget

image

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 or @bhardwajaditya can you take a quick look at this please?

**Review by Shailesh351 — APPROVED** [review]
Looks good to me. Just a suggestion Instead of `Enable Avatar`, `Show Avatar` sounds better

**Comment by Shailesh351** [comment]
@ItzzRitik This PR should be against the `ui_refactor` branch, Right?

**Comment by itzzritik** [comment]
Hi @Shailesh351,
Since this change is a part of another PR for Live Chat Widget ->  [PR LINK](https://github.com/WideChat/Rocket.Chat.Livechat/pull/94)

and since there is no separate branch for the LiveChat widget hence I did the same for this switch as well
But I'm open to suggestions, please let me know if we want this change to go into [ui_refactor](https://github.com/WideChat/Rocket.Chat/tree/ui_refactor) Branch

**Comment by Shailesh351** [comment]
@ItzzRitik Ohh yes, I forgot that it's for Livechat. "Friendly Chat" confused me 😅

**Review by Shailesh351 — APPROVED** [review]

**Comment by ear-dev** [comment]
@ItzzRitik @Shailesh351 this looks great.  I will merge after the corresponding Livechat PR gets fixed and approved.  Thanks!

**Pull request merged**
