### PR TITLE
[Upstream Catchup] Merge RC:master to develop_pwa

### PR DESCRIPTION
**Pull request by ear-dev**
Weekly Catchup PR to merge RC:master in develop_pwa.

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 We must fix the issue where server restart required for new app settings to take hold.

**Comment by Shailesh351** [comment]
@bhardwajaditya I have pushed the latest commits

**Comment by ear-dev** [comment]
Issues: 

- Log level not being abided. 
- App settings in config.json not being abided by until restart....  (might be fixed now?  please test by changing the welcome message and verify)

**Comment by bhardwajaditya** [comment]
@ear-dev the above mentioned two bugs are there but they are not related to this PR. This looks good to go.

1. App settings bug will be fixed by https://github.com/WideChat/Apps.Dialogflow/pull/149

2. Log levels not abided - seems like we lost this in catchup merge of apps-engine. I am debugging this one and will raise a PR there.

**Comment by Shailesh351** [comment]
@bhardwajaditya @ear-dev I just observed one thing, when I open `http://localhost:3000/home` it shows a blank screen

Screenshot 2022-03-25 at 11 38 19 AM

**Comment by ear-dev** [comment]
Thanks for looking at that @Shailesh351 I will also test.  @bhardwajaditya is that what you are finding as well?

**Comment by bhardwajaditya** [comment]
@ear-dev yeah same for me. Nice catch @Shailesh351 . Looking into it

**Comment by ear-dev** [comment]
@bhardwajaditya we will merge this PR as is......  but please verify after the merge, that all our dependencies are up to date:  apps.engine, livechat.  If needed, please make a new PR for them.....  after this PR is merged.

**Review by bhardwajaditya — APPROVED** [review]

**Comment by Shailesh351** [comment]
I have created PR to fix the settings not being applied issue https://github.com/WideChat/Rocket.Chat/pull/1132

**Pull request merged**
