### PR TITLE
[BREAK] Revert PWA changes

### PR DESCRIPTION
**Pull request by bhardwajaditya**
## Issue(s)
Closes: https://github.com/WideChat/Rocket.Chat/issues/1267

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya Based on what you enumerated in the issue, this PR represents a TOTAL rollback of our PWA changes? So there are no other issues to be dealt with in the next merge with 5.x, except maybe a few cypress tests we can remove?

**Comment by ear-dev** [comment]
@bhardwajaditya FYI - I'll test this PR against our testbot.

**Comment by bhardwajaditya** [comment]
@ear-dev yes this is total rollback apart from the cypress tests

**Comment by ear-dev** [comment]
@bhardwajaditya can you double check that we did not lose the changes for showing the transcript button in the widget at the end of a chat?  And the changes for disabling the options menu in the widget as well please?  

I'm testing this branch and so far I can't get it to show the button, and I think my admin configs are correct...... but I suppose all of that is in the livechat repo, so should not be affected by these changes?  Although the settings on on the server....

**Comment by bhardwajaditya** [comment]
@ear-dev I have done the catchup, let me know if the errors still persist

**Comment by ear-dev** [comment]
@bhardwajaditya 
```
Unable to resolve some modules:

  "@rocket.chat/apps-engine/server/bridges/AnalyticsBridge" in /Users/erosenthal/Git/WideChat/Rocket.Chat/app/apps/server/bridges/analytics.ts (os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save @rocket.chat/apps-engine
```

Do you need to update your apps-engine version?

Oh wait.....  my bad....  I probably need to run meteor npm install again.....  sorry

**Comment by ear-dev** [comment]
@bhardwajaditya I'm pretty sure that I have verified that we have lost a bunch of features related to chat closing behavior.  

- the options menu still appears in the widget
- the transcript button is not presented at the end of a chat
- clicking the "X" automatically minimizes the chat window, although we changed that behavior to leave the window visible so the visitor could click the Save Transcript button

Can you also verify these things please?  thanks.

**Comment by Shailesh351** [comment]
@bhardwajaditya Can you please check the build failure? Thankss!

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya Can you please check if we need to remove changes from the below files?

1. In server/importPackages.ts -> import '../app/contacts/server';
2. packages/rocketchat-i18n/i18n/en.i18n.json 
3. lib/callbacks.ts
4. client/importPackages.ts ui-share
5. client/head.html
6. client/hooks/useSession.js useUserId.js useUserPreference
7. app/contacts/server/index.js contacts sync http://localhost:3000/admin/Contacts 

The main two features still not removed are `ui-share` and `Contacts`

@ear-dev LiveChat Widget is working fine in my local. I'm not seeing issues you have mentioned

**Comment by ear-dev** [comment]
NOTE:  This PR needs eventually to be tested against the testbot before we merge.

**Comment by bhardwajaditya** [comment]
@Shailesh351 contacts was not part of PWA development and same goes for share, so that's why I didn't remove those two changes

**Comment by Shailesh351** [comment]
> @Shailesh351 contacts was not part of PWA development and same goes for share, so that's why I didn't remove those two changes

Yeah, It's not actually related to PWA. But these features are added by us and we are not using them. So we should remove it as well.

**Comment by Shailesh351** [comment]
@bhardwajaditya Can you please merge the latest develop branch in your branch so that other changes do not appear in your PR? Thanks!

**Comment by Shailesh351** [comment]
@bhardwajaditya Can you check if current changes in the below files are still needed? you can compare current develop_pwa with 4.6.3 to check the changes.

3. lib/callbacks.ts
5. client/head.html
6. client/hooks/useSession.js useUserId.js useUserPreference

**Comment by ear-dev** [comment]
> @bhardwajaditya Can you please merge the latest develop branch in your branch so that other changes do not appear in your PR? Thanks!

do you mean the latest develop_pwa changes? or maybe I'm misunderstanding what you're seeing....

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya Can you check if current changes in the below files are still needed? you can compare current develop_pwa with 4.6.3 to check the changes.
> 
> 3. lib/callbacks.ts
> 4. client/head.html
> 5. client/hooks/useSession.js useUserId.js useUserPreference

@Shailesh351 Yes I see they are part of catchup as well. They are required going further

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya I'm sharing some screenshots which show the diff between upstream 4.6.3 and the pwa_revert branch, and I think some changes are not needed anymore which we should remove. I understand it will be difficult for you to switch to this one again. Can you please whenever you get a chance? Maybe we should get done with this asap so you don't need to keep switching again and again. Thanks...


Screenshot 2022-09-10 at 4 31 05 PM
Screenshot 2022-09-10 at 4 32 32 PM
Screenshot 2022-09-10 at 4 35 14 PM
Screenshot 2022-09-10 at 4 36 15 PM
Screenshot 2022-09-10 at 4 38 28 PM
Screenshot 2022-09-10 at 4 40 56 PM
Screenshot 2022-09-10 at 4 41 20 PM
Screenshot 2022-09-10 at 4 42 06 PM
Screenshot 2022-09-10 at 4 43 02 PM
Screenshot 2022-09-10 at 4 44 10 PM
Screenshot 2022-09-10 at 4 45 31 PM

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya All the things look good just two last things please

- discoverability not wholly removed
- web-push dependency is not being used anywhere. Can you please confirm and remove it from package.json?

Thanks...

**Comment by ear-dev** [comment]
this is ready to be tested. @ear-dev will test. @Shailesh351 will give it a final review.

**Comment by Shailesh351** [comment]
@bhardwajaditya We also don't need `Accounts_Default_User_Preferences_discoverability` setting right? It's part of discoverability. Also discoverability in `tests/end-to-end/api/00-miscellaneous.js`

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 I tested this branch with the testbot multiple times and it is passing.  I'm good to merge this into develop after @Shailesh351 approves. Thanks!  Step one...... :-)

**Comment by Shailesh351** [comment]
> @bhardwajaditya @Shailesh351 I tested this branch with the testbot multiple times and it is passing.  I'm good to merge this into develop after @Shailesh351 approves. Thanks!  Step one...... :-)

@ear-dev I'm waiting for Aditya's changes for https://github.com/WideChat/Rocket.Chat/pull/1281#issuecomment-1255803191

**Review by Shailesh351 — APPROVED** [review]
LGTM! We can remove pending items separately or if it's quick, we can wait for that

**Comment by bhardwajaditya** [comment]
@Shailesh351 i will make these changes by evening, I couldn't do it since changing branches resets the DB , I was in middle of catchup issue

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 As we discussed in the chat room, I am going to merge this now and make a note of the two remaining functionalities that will need to be removed.  Thank you @bhardwajaditya !

**Pull request merged**
