### PR TITLE
Fix profile picture cache

### LINKED ISSUE #239: Unable to see the updated profile picture. The cache storage is not updating to new profile.

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #239

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you review this one as well please?  Thanks.

**Comment by Shailesh351** [comment]
@shubhsherl  I'm not able to test it properly. In the offline mode stylesheet it not fetched, so it looks like this. Offline mode is working fine in develop_pwa.
Screenshot 2020-05-05 at 12 36 08 AM

**Comment by shubhsherl** [comment]
@Shailesh351 It should work now. Mea culpa, I used "no-cache", which disables the cache while fetching. "reload" will use cache(if available), and update from the network for future use.

**Comment by ear-dev** [comment]
@shubhsherl Can you resolve the conflicts please?

**Comment by shubhsherl** [comment]
@ear-dev I've resolved the conflict.

**Comment by Shailesh351** [comment]
@shubhsherl offline mode issue is not happening now.

When I change profile pic it is not directly update on top left thumbnail. When I change status then it's getting updated. And after that when i refresh it's changed back to previous one. I have attached gif for the same

Screen-Recording-2020-05-11-at-1

**Comment by shubhsherl** [comment]
@Shailesh351 I am using [Stale while revalidate](https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook#stale-while-revalidate) method to update the cache. So in the first refresh, you will see the old response, but after the second refresh, the updated response will be provided. 

> When I change profile pic it is not directly update on top left thumbnail.

Let me check this issue.

**Comment by ear-dev** [comment]
@Shailesh351 @shubhsherl Where are we with this PR?

**Comment by Shailesh351** [comment]
@shubhsherl Any update on the above issue?

**Comment by shubhsherl** [comment]
> @shubhsherl Any update on the above issue?

@Shailesh351 Could not figure out why the top thumbnail is not updating. The same [function](https://github.com/WideChat/Rocket.Chat/blob/develop_pwa/app/ui-utils/client/lib/avatar.js) is used in message avatars and the top thumbnail. Also, as mentioned in the channel, avatar updates after a few seconds even the cache is updated. 
https://drive.google.com/file/d/17l_clh6-3BxPcVx-zLNQ5RiIDh-c73UD/view?usp=sharing

**Review by Shailesh351 — APPROVED** [review]
Changes looks good. For the new issue we found we can have separate PR for that

**Pull request merged**
