### PR TITLE
[Upstream Catchup] Merge RC:master to develop_pwa

### PR DESCRIPTION
**Pull request by ear-dev**
Weekly Catchup PR to merge RC:master in develop_pwa.

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you verify this PR for us please?

**Comment by ear-dev** [comment]
@bhardwajaditya can you look at the build failure please?  thanks...

Also, can you cleanup please by closing any of the catchup merge PRs that are no longer needed or valid?

**Comment by ear-dev** [comment]
@Shailesh351 please make a note here about adding the properties we might need to pass the lint checks....  thanks.

**Comment by Shailesh351** [comment]
```
Error: client/views/omnichannel/triggers/TriggersForm.stories.tsx(34,4): error TS2741: Property 'department' is missing in type '{ sender: string; msg: string; name: string; }' but required in type '{ sender: string | undefined; department: string | undefined; msg: string | undefined; name: string | undefined; }'.
Error: client/views/omnichannel/triggers/TriggersForm.stories.tsx(41,2): error TS2741: Property 'handleRegisteredOnly' is missing in type '{ handleName: HandlerFunction; handleDescription: HandlerFunction; handleEnabled: HandlerFunction; handleRunOnce: HandlerFunction; handleConditions: HandlerFunction; handleActions: HandlerFunction; }' but required in type '{ handleName: (event: FormEvent<HTMLInputElement>) => void; handleDescription: (event: FormEvent<HTMLInputElement>) => void; ... 4 more ...; handleActions: (value: TriggerActions) => void; }'.
Error: client/views/omnichannel/triggers/TriggersForm.tsx(71,23): error TS2304: Cannot find name 'SelectOptions'.
```
@bhardwajaditya  The build issue is because of 
`department`, `handleRegisteredOnly` is defined here https://github.com/WideChat/Rocket.Chat/blob/develop_pwa/client/views/omnichannel/triggers/TriggersForm.tsx#L23...L45

but missing in https://github.com/WideChat/Rocket.Chat/blob/develop_pwa/client/views/omnichannel/triggers/TriggersForm.stories.js

**Comment by ear-dev** [comment]
@bhardwajaditya still working on this one?

**Comment by ear-dev** [comment]
@bhardwajaditya please find the root cause of the latest failures because, as you suggest, these tests were added by us, and maybe this is an indication that we have lost something in the merge.

**Comment by ear-dev** [comment]
@bhardwajaditya Any luck with this?  Is there a chance we can wrap this one up soon?  Thanks....

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya Any luck with this? Is there a chance we can wrap this one up soon? Thanks....

@ear-dev on it

**Comment by bhardwajaditya** [comment]
@ear-dev this is fixed after removing the action

**Comment by ear-dev** [comment]
@bhardwajaditya I tested this against our testbot and everything is passing, so looks good to me.  Nice job!  thanks....  @Shailesh351 is there anything you would like to look at before we consider merging this?

**Comment by ear-dev** [comment]
@Shailesh351 do we think this is ready to merge?  It might be a good time to do it I think.  At that point you will need to catchup with in the sns_logging_master branch

**Comment by ear-dev** [comment]
@Shailesh351 have you had a chance to look at this yet?  Just checking....  thanks.

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya @ear-dev I found some issues which are just lost changes while fixing merge conflicts. 

1. In the `login.page.js` file below `warningAlert` fn is removed, which is being used in `tests/cypress/integration/00b-login-offline.js` `loginPage.warningAlert.should('be.visible');`

```
get warningAlert() {
        return browser.element('.alert-warning');
    }
```

2. In `.github/pr-title-checker-config.json` “Upstream Catchup” is not there. I remember we added it.
https://github.com/WideChat/Rocket.Chat/commit/10d538407b9cb0489a3caaeed95836db5e574e3c

3. We lost `acc-ecr-push` in the `.github/workflows/build_and_test.yml`, which pushes builds to our docker
```
acc-ecr-push:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop_pwa' && github.event_name == 'push' }}
    needs: test
```

4. In the `app/lib/server/functions/insertMessage.js` we had check for message object and we added one property `pushm: Boolean,` in it. This check was moved to another file `app/lib/server/functions/sendMessage.js` `validateMessage fn`. And that properties is not there.

5. In the `app/models/client/models/Roles.js` file `const role = this.findOne(name);` but we are not getting `name` as fn argument we are getting `roleId`

6. The `SideNav.js` file is refactored to `SideNav.ts`. We added some changes in SideNav.js https://github.com/WideChat/Rocket.Chat/commit/9f546529542fb73c7311e3706f6698378c7bdbbd and in the .ts file we are not having it. Can you confirm if still require or it’s not more needed?

7. The `getUserInfo.js` was refactored to `getUserInfo.ts`. We added some changes in .js file we are not in .ts.

**Comment by ear-dev** [comment]
@bhardwajaditya any chance we'll have this ready today or tomorrow?

**Comment by bhardwajaditya** [comment]
@ear-dev yes for sure

**Comment by ear-dev** [comment]
@Shailesh351 just want to get this done if possible before you're out next week......  thanks!

**Review by Shailesh351 — APPROVED** [review]
Looks good to me. Working fine locally.

**Pull request merged**
