### PR TITLE
Livechat: Client-side filters and session start trigger

### PR DESCRIPTION
**Pull request by dlassalle**
Another round of updates from develop_livechat

### CODE REVIEW

**Review by shubhsherl — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]
Looks good to me.

Upstream is moved to react on Admin Omnichannel. Just make sure to merge after https://github.com/WideChat/Rocket.Chat/issues/389. So we know if there is any modification needed at our side or not.

**Comment by Shailesh351** [comment]
@ear-dev @dlassalle Should we keep develop_pwa as common branch for both livechat and pwa? Let me know your thoughts

**Comment by ear-dev** [comment]
@Shailesh351 @dlassalle It looks like we have conflicts after catchup with Upstream.  Shailesh do you want to take a look?  David, you will want to catchup with the develop_pwa branch on any branches you guys have been working on that are destined for WideChat.

@Shailesh351 are you suggesting that we all start working directly off the develop_pwa branch, and stop using the develop_livechat branch?  That might make sense.  @dlassalle what do you think? 

Are you also maintaining a branch that you can push upstream?  Unfortunately, our WideChat branch has diverged in such a way that we are not making PRs upstream from it, but instead re-creating any feature branches and PRs from the upstream develop branch when needed....  or vice-versa....

**Comment by dlassalle** [comment]
@ear-dev working off pwa probably makes sense, im looking at resolving these conflicts now. 
I'm not maintaining a branch to push upstream currently

**Comment by Shailesh351** [comment]
> @Shailesh351 are you suggesting that we all start working directly off the develop_pwa branch, and stop using the develop_livechat branch? That might make sense. @dlassalle what do you think?

Yes @ear-dev. By this we can avoid efforts maintaining separate branch for livechat. which is eventually going to merge into develop_pwa

**Comment by Shailesh351** [comment]
@dlassalle @shubhsherl This conflicts are because RC core is being rewritten to React. Also Max Char Limit Feature is affected.

**Comment by shubhsherl** [comment]
@ear-dev Yeah, we, anyway, are merging the changes from livechat to pwa, it will be a good idea to work on pwa.

**Comment by dlassalle** [comment]
@Shailesh351 or @shubhsherl do one of you mind looking at these conflicts? I think the changes are a little beyond my ability to efficiently resolve

**Comment by shubhsherl** [comment]
@dlassalle Sure

**Comment by shubhsherl** [comment]
Closing in favour of #400

**Pull request closed without merging**
