### PR TITLE
[FIX] Fix chat close stuck issue

### LINKED ISSUE #1367: [BUG][Mobile app Android] Stuck in 'Chat already closed. Please start a new chat'
If I let the session timeout on the android mobile app, then I get a message in the space where the composer is that says:  'Chat already closed. Please start a new chat'

However there is no way to start a new chat.  No button to push, and navigating away from the widget back into the app, and then back again does not help.  Even if I log out of the app, and back in, I'm still stuck.  I think I have to delete all app data to get back to a state where I can use the chat again.

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes: https://github.com/WideChat/Rocket.Chat/issues/1367

## Steps to test or reproduce

1. Start a chat
2. In rocketchat_room mongo collection set open flag to false
3. Send a message in the livechat window

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya I tested this and it is working for when the visitor types into the empty room.  In that case the room just closes and the widget is minimized.  I don't actually have a way to test this from within the mobile app to verify the behavior, but it's looking good so far. 

One issue:  If I try to close the room using the 'X', then it gets stuck with the "Error closing chat" message.  Should we account for that as well?

Also:  I'm still seeing the red error banner at the top of the room, even after it has been auto closed by this fix.  It eventually goes away after 20 seconds or so, but can we get rid of that in this case as well?

**Comment by bhardwajaditya** [comment]
@ear-dev yes we should fix that cross thing as well, no where it should block a user. I will remove that alert as well

**Comment by bhardwajaditya** [comment]
@ear-dev updated the PR with the two fixes you mentioned above

**Comment by ear-dev** [comment]
Perfect!  Works great.  Thanks!

**Review by ear-dev — APPROVED** [review]

**Pull request merged**
