### PR TITLE
Fix UserInfo on mobile device

### LINKED ISSUE #285: Clicking on user avatar opens Keyboard

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #285

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl I am not able to reproduce the problem you have fixed here.....  can you show me what the original issue was?

**Comment by shubhsherl** [comment]
@ear-dev Click on user avatar in a message, it will open the user-info page and also the keyboard.

**Comment by ear-dev** [comment]
@shubhsherl  Hmmm.....  I am not able to reproduce this.

**Comment by shubhsherl** [comment]
@ear-dev 
output

**Comment by ear-dev** [comment]
Thanks @shubhsherl

**Pull request merged**
