### PR TITLE
Fix double popover message action

### LINKED ISSUE #286: Double-tap on a message opens two popover which freezes the app.

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #286

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl I have seen the app freeze with the popover open, but I am not able to reproduce the bug on demand.  Do you have an easy repro you can show me?

**Comment by shubhsherl** [comment]
@ear-dev Double tap on any message to reproduce it.

**Comment by ear-dev** [comment]
@shubhsherl I am not able to reproduce this at will unfortunately. @Shailesh351 can you take a look at this one as well please?

**Review by Shailesh351 — APPROVED** [review]
LGTM 🎉

**Comment by Shailesh351** [comment]
@ear-dev I'm able to reproduce the bug and able to test the fix. It is working fine. 
Thanks @shubhsherl 😄

**Pull request merged**
