### PR TITLE
Some recent fixes in develop_pwa

### PR DESCRIPTION
**Pull request by shubhsherl**
Updating some recent fixes from develop_pwa to upstream.
#247 #293 #288 #287

### CODE REVIEW

**Comment by ear-dev** [comment]
@shubhsherl did all of these fixes also get into the actual upstream PRs with RocketChat?

**Comment by ear-dev** [comment]
@Shailesh351 can you take a quick look an approve this one please?

**Comment by shubhsherl** [comment]
> @shubhsherl did all of these fixes also get into the actual upstream PRs with RocketChat?

@ear-dev Updated https://github.com/RocketChat/Rocket.Chat/pull/17549 and https://github.com/RocketChat/Rocket.Chat/pull/17269

**Comment by Shailesh351** [comment]
Will do @ear-dev

**Review by Shailesh351 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
