### PR TITLE
Upstream Catchup PR for 3.8.1

### PR DESCRIPTION
**Pull request by Shailesh351**

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 did this come from our usual monday auto merge?

**Comment by Shailesh351** [comment]
> @Shailesh351 did this come from our usual monday auto merge?

No @ear-dev I have created this PR from the local branch I were working on.

Strange there is no regular Catch-up PR this Monday. upstream has already released 3.8.0. Let me check.

**Comment by Shailesh351** [comment]
@ear-dev I can see the workflow has been disabled manually.

IMG_20201118_132137

**Comment by ear-dev** [comment]
@Shailesh351 yeah, I noticed that......  I have no idea how that got disabled, do you?

Have you been able to test this merge a little bit?  I understand that our PWA UI will be reverted because this is after the sidebar refactor, right?  Just let me know if this is ready to merge please. 

FYI - we're still working on the new UI for the PWA homescreen, but I think when it's ready we should be able to start implementing because there should not be more refactors coming.

We still have to wait on UI changes to the chatrooms however, since the refactor for that is still pending I believe.

**Comment by ear-dev** [comment]
@Shailesh351 let me know when this is ready to merge..... thanks for pulling it manually. Probably we should re-enable the auto merge unless there is a reason it was originally disabled.

**Comment by Shailesh351** [comment]
@ear-dev We are good to merge this one. Only header search which is always visible in our PWA is missing. We can work on it after the new design of home screen is finalized.
I'm not able to approve as I have created this PR. Can you do it please? We can enable the catchup workflow then. Thanks 😄

**Comment by ear-dev** [comment]
@Shailesh351 great!  Thanks for looking at it...  I will re-enable the auto catchup action after I merge this.

**Pull request merged**
