### PR TITLE
[FIX] Build and test workflow after upstream catchup v4.8.1

### PR DESCRIPTION
**Pull request by ear-dev**
Part of https://github.com/WideChat/Rocket.Chat/issues/1329

### CODE REVIEW

**Review by Shailesh351 — COMMENTED** [review]
@ear-dev The build is failing at `yarn install`. I was facing the same issue while setting up locally.

Updating the git config worked for me `git config --global url."https://".insteadOf git://`
Reference: https://github.com/Polymer/polymer/issues/1468#issuecomment-97661440

**Comment by ear-dev** [comment]
> @ear-dev The build is failing at `yarn install`. I was facing the same issue while setting up locally.
> 
> Updating the git config worked for me `git config --global url."https://".insteadOf git://` Reference: [Polymer/polymer#1468 (comment)](https://github.com/Polymer/polymer/issues/1468#issuecomment-97661440)

Thanks @Shailesh351 testing now

**Comment by ear-dev** [comment]
@Shailesh351 we made it past yarn install, now failing on yarn lint.  Do you know what 'rocketchat-services' represents?  Any ideas about the failure?  Seems to be a typescript error.  Thanks.

**Comment by Shailesh351** [comment]
> @Shailesh351 we made it past yarn install, now failing on yarn lint. Do you know what 'rocketchat-services' represents? Any ideas about the failure? Seems to be a typescript error. Thanks.

@ear-dev `rocketchat-services` is one of the RC packages part of the mono repo. The error we are getting is due to the lint issue. Somehow it's scanning for lint issues inside the `node_modules` folder, which it should not.

**Comment by ear-dev** [comment]
@Shailesh351 looking at the current upstream workflow they have something different in this spot.  maybe they fixed a bug that we have not caught up with yet?  https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/workflows/build_and_test.yml#L148

**Comment by Shailesh351** [comment]
@ear-dev I checked upstream with version 4.8.1 and also with the latest version. There is no fix. When I ran upstream 4.8.1, it works. So the issue is at our end. I'm looking into it 👍

**Comment by Shailesh351** [comment]
@ear-dev The build failure issue is now fixed. Can you please review it whenever you get a chance? Thanks!

**Comment by ear-dev** [comment]
Thanks @Shailesh351 great work!
Does this include all the fixes from https://github.com/WideChat/Rocket.Chat/issues/1329 as well?  It looks like it includes some of them at least?

**Comment by Shailesh351** [comment]
It doesn't include all the fixes for 1329, only what required for the build to work.

**Pull request merged**
