### PR TITLE
Add custom oauth API

### PR DESCRIPTION
**Pull request by bhardwajaditya**

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya Did you document how to use the new API?  I thought you did, but I'm not finding it right now.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev please refer the wiki through the link below
https://github.com/WideChat/Rocket.Chat/wiki/Custom-OAuth-API-usage

**Comment by ear-dev** [comment]
@bhardwajaditya This works great.  Thanks. 

Couple of issues though:
1) "tokenSentVia", "loginStyle", and "keyField" are drop downs in the UI.  Is there a mapping for the potential values that I can use in the API?  Can you add that to the wiki please?
2) "merge roles from SSO" - is that an option we can pass in the API.... it is in the UI.  If so, can you add that to the wiki please?
3) "rolesClaim", "groupsClaim", and "channelsAdmin" seem like ambiguous naming conventions to me.  Granted, I don't actually know yet what those fields do......  but can we change them to more closely align with what I'm seeing in the UI?  Or maybe this is how they are mapped in the RC server itself right now, so it makes sense to keep them the way you have them?

Do you think this is a good feature to make an upstream PR?

Thanks!

**Review by ear-dev — APPROVED** [review]
@bhardwajaditya I figured out my issue with the dropdowns......  I was using Uppercase "Header" instead of "header" for example. 

this looks good to me......  I'll merge. Thanks!!

**Pull request merged**
