### PR TITLE
Adjust font sizes and toolbar spacing for mobile

### PR DESCRIPTION
**Pull request by ear-dev**

### CODE REVIEW

**Comment by Shailesh351** [comment]
@ear-dev There is some flickering in font-size at width 400 px. And also channel name font size is big and overflowing from the Text box.(Attached screen shot).

Also just suggestion Header icons are looks small. like profile image looks smaller that search bar

Screenshot 2020-02-14 at 10 02 48 AM

**Comment by ear-dev** [comment]
@Shailesh351 Thanks for testing.  I'll take a look.

**Comment by ear-dev** [comment]
Strange thing.....  I'm not seeing the most recent message showing up in my rooms list view.  So I'm also not able to reproduce the overflow you are seeing because I think that is what is blocking the font.  Not sure why I'm not getting the most recent message.

**Comment by ear-dev** [comment]
@Shailesh351 I am not able to reproduce the overflow issue you have flagged.  Can you send me the exact specs on an emulator that would reproduce?

**Comment by ear-dev** [comment]
@Shailesh351 I adjusted a few things. Can you take another look please when you get a minute. Thanks.

**Comment by ear-dev** [comment]
We're going to merge this today so we can deploy a new prototype..... feel free to comment on anything that needs to be fixed and we'll make another PR

**Pull request merged**
