### PR TITLE
Chore: push to ecr from the develop branch

### PR DESCRIPTION
**Pull request by ear-dev**

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya So it looks like we haven't had the tests enabled.......  sorry about that, I should have picked that up.  I've adjusted the workflow so that it runs the tests, and hopefully runs our ECR push job when successful on the develop branch.  But in the meantime, yarn install, is failing in the test jobs.  Can you take a look please?  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev it seems that build and test is disabled after your last commit

**Comment by ear-dev** [comment]
> @ear-dev it seems that build and test is disabled after your last commit

how on earth did that happen?  I'm looking at all that now.

Ok, I introduced a syntax error....  back to working, but I'm still tweaking the workflow file.

**Comment by ear-dev** [comment]
@bhardwajaditya I've fixed the yarn issue, but we seem to have other issues with the tests, at the point they are trying to build a test container I think. 

I've reverted most changes I had originally made to the workflow file, in order to get back to some baseline.  I'm just not sure if we need 'build-image-pr', but I put it back for now just in case, while we're debugging the other jobs.  Can you take a look at these errors after the current run please?  thanks. 

NOTE:  I have also updated the use of 'set-output' in the workflow files, but that is mostly just tech debt as we were getting warnings about that feature being deprecated in favor of using the new syntax.

**Comment by ear-dev** [comment]
@bhardwajaditya I was able to fix the out of memory error and now the tests are running properly.  So far I am seeing at least one test failure that we need to look into please, thanks.   I believe it's this test that is failing:  https://github.com/WideChat/Rocket.Chat/blob/develop/apps/meteor/tests/end-to-end/api/16-commands.js#L38

`{
  lastUrl: '/api/v1/commands.get',
  lastResponse: '{"success":false,"error":"There is no command in the system by the name of: help"}'
}
  817 passing (3m)
  4 pending
  1 failing
  1) [Commands]
       [/commands.get]
         should return success when parameters are correct:
     Error: expected 200 "OK", got 400 "Bad Request"`

**Comment by ear-dev** [comment]
@bhardwajaditya can you please show me in the RC admin UI where we can set 'disable composer' while we wait for the welcome event?  I know we set something in the DF.app, but it seems like we are failing the upstream livechat tests because we have a default value to disable the composer.  But if we also have an admin switch, we can revert the setting to allow the tests to pass?

@bhardwajaditya please check RC upstream build_and_test.yaml and notice their dummy license which we can use to run enterprise tests.  See if you can cherry pick this build step, or the portion we need, to get our tests to pass.

**Comment by ear-dev** [comment]
Status:  We will comment out a handful of livechat widget UI tests which are currently failing because we have hard coded the 'disable_composer' while waiting for the welcome event. Our thought is that we already cover these tests in our test_bot suite.

**Comment by ear-dev** [comment]
Passed!  I'll merge and we'll test again in develop......  @Shailesh351 if the build and tests pass after the merge I think it's ready for you to have a look.  Thanks!

**Pull request merged**
