### PR TITLE
[FIX] Fix PWA bugs

### LINKED ISSUE #861: [BUG] PWA sometimes needs refresh to see room messages

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Issue Link - https://github.com/WideChat/Rocket.Chat/issues/861

## Proposed changes (including videos or screenshots)

- Fix offline message sending, was broken currently messages sent offline were not sent to the user upon reconnection
- Refresh was required to reload messages. Shifted to a hybrid approach rather than full caching as compared to current implementation
- Message prefetching was broken since the callback was removed in upstream. Migrated from the callbacks approach

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you review please?  Thanks...

**Comment by Shailesh351** [comment]
@bhardwajaditya While testing I found that in the offline mode, earlier app was showing old messages. But not it is now showing old messages. Can you please check? Also can you please fix the conflicts as well?

Screenshot 2021-11-01 at 4 49 06 PM

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya While testing I found that in the offline mode, earlier app was showing old messages. But not it is now showing old messages. Can you please check? Also can you please fix the conflicts as well?
> 
> Screenshot 2021-11-01 at 4 49 06 PM

Can you please give steps to reproduce this issue

**Comment by Shailesh351** [comment]
> Can you please give steps to reproduce this issue

@bhardwajaditya 

1) Open Web App and open any chat (loading messages)
2) In the dev tools, change network to offline.
3) Reload page. It keeps showing the loading indicator. Earlier it was showing chat history

**Comment by bhardwajaditya** [comment]
@Shailesh351 fixed these bugs

**Comment by ear-dev** [comment]
@Shailesh351 can you take another look at this PR please and approve if you think it's ready?  thanks.

FYI - Aditya is out this week, and I see that there is a conflict in package-lock.......  can you just resolve that conflict during your review?  thanks..

**Review by Shailesh351 — APPROVED** [review]
Looks good to me. Above issue is resolved now.

**Comment by ear-dev** [comment]
@Shailesh351 when I try your test in offline mode, I'm not seeing any chat history.  I went to a chat, toggled into offline mode, then hit refresh on the browser.  Is that the correct test?  Can you describe the expected behavior again please?  thanks...

**Comment by Shailesh351** [comment]
@ear-dev Yes that's the correct test. It should show the chat history which the user was seeing before going offline.  It is working for me.

If you are testing locally, offline service worker does not work with `meteor npm start`. It works with production `meteor run --production`.

**Comment by ear-dev** [comment]
Oh wow.......  I never heard of 'meteor run --production'.....  can you describe to me how it differs from meteor npm start?

**Comment by Shailesh351** [comment]
`meteor npm start` just starts dev server in which we can attach the debugger and all. `meteor run --production` runs production app locally with all the bundling, minifying, etc. It simulates production locally.

**Pull request merged**
