### PR TITLE
[NEW] Upstream catchup v5.1.0

### LINKED ISSUE #1245: [Upstream Catchup] RC server

### PR DESCRIPTION
**Pull request by bhardwajaditya**
## Issue(s)
Closes: https://github.com/WideChat/Rocket.Chat/issues/1245

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya I got this error trying to run this server......  
` Error: Cannot find module '/home/ubuntu/Rocket.Chat/apps/meteor/node_modules/@rocket.chat/agenda/dist/index.js'. Please verify that the package.json has a valid "main" entry`

Any ideas?

**Comment by bhardwajaditya** [comment]
@ear-dev what is the sequence of commands you used?

**Comment by ear-dev** [comment]
> @ear-dev what is the sequence of commands you used?

yarn install; yarn dev

**Comment by bhardwajaditya** [comment]
This works for me that's strange. Let me check again

**Comment by bhardwajaditya** [comment]
@ear-dev try yarn build once before running yarn dev

**Comment by ear-dev** [comment]
> @ear-dev try yarn build once before running yarn dev

That worked.....  thanks!

**Comment by ear-dev** [comment]
@bhardwajaditya Even though the server starts for me now, all I get when I navigate to the home page is a blank screen.  Any ideas?

image

**Comment by bhardwajaditya** [comment]
@ear-dev that's strange it works for me perfectly fine. This import error shouldn't be there as this file is available.

**Comment by ear-dev** [comment]
@bhardwajaditya I'm still having trouble getting this to run.  Now I can't run `yarn build` anymore... I get this error:

`rocketchat-services:build: ../../../server/models/raw/BaseRaw.ts(264,5): error TS2769: No overload matches this call.                                                     
rocketchat-services:build:   Overload 1 of 4, '(filter: Filter<RocketChatRecordDeleted<T>>, update: Partial<RocketChatRecordDeleted<T>> | UpdateFilter<RocketChatRecordDel
eted<T>>, callback: Callback<...>): void', gave the following error.                                                                                                      
rocketchat-services:build:     Argument of type '{ $set: RocketChatRecordDeleted<T>; }' is not assignable to parameter of type 'Partial<RocketChatRecordDeleted<T>> | Upda
teFilter<RocketChatRecordDeleted<T>>'.                                                                                  `

**Comment by bhardwajaditya** [comment]
@ear-dev it seems something is broken in your build. Delete all node_modules in sub directories and try again. I have seen these errors but they don't exist anymore they are fixed.

**Comment by ear-dev** [comment]
> @ear-dev it seems something is broken in your build. Delete all node_modules in sub directories and try again. I have seen these errors but they don't exist anymore they are fixed.

I just started from scratch cloning the repo into a new directory, and I'm still seeing the same issue?  Is there any chance you lost some fix in your latest?

**Comment by ear-dev** [comment]
@bhardwajaditya I found an issue in the widget in regard to escalated timeout.  The timeout banner does not disappear after the timeout has been reached.  Can you take a look please?

image

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 FYI - this branch has passed all the testbot test cases except that one timeout warning banner issue. So from my perspective, after that is fixed, I'm good.

**Comment by bhardwajaditya** [comment]
@ear-dev the timeout warning issue is fixed.

**Comment by ear-dev** [comment]
@bhardwajaditya can you also look at this previous fix we made for character handling in the widget, I think we don't have this one in the catchup branch.  I'm seeing funky characters...  https://github.com/WideChat/Rocket.Chat/issues/1308
thanks.

**Comment by Shailesh351** [comment]
@bhardwajaditya I found following issues

- [ ] Roomid column is missing in omnichannel current chats. It was there earlier
- [ ] Livechat filter is not opening
- [ ] Is @kossnocorp/desvg being used in livechat?

Can you please also check build failure?

**Comment by ear-dev** [comment]
@bhardwajaditya can you comment here please about your fix for the timeout banner issue?  It's useful for tracking.... thanks!

**Comment by bhardwajaditya** [comment]
For livechat banner, we were calling logger.sendLogsToEs which was importing aws4 library which was not compatible with the mono repo, since we are not using this feature, all calls to the above function is removed, the logs are still accumulated on client side but they won't be sent and the server side functions are still intact.

**Comment by ear-dev** [comment]
Status: Aditya please disable any auto tagging in the workflows, we don't need that.  Figure out what token and where is required for turbo server (integration tests).

**Comment by ear-dev** [comment]
@bhardwajaditya I am still seeing the timeout warning banner issue on escalated sessions.  The error seems different this time....  failed to load custom field resource it seems...  any ideas?

Did we lose the custom-field endpoint?  I also was not able to use it in my version controller. 

image

**Comment by ear-dev** [comment]
Issue: we need to disable the widgets function to close a room after a timeout of an escalated session.  The custom field is still needed to tell the widget to remove the timeout banner if it is visible.  this is because we have configured the SF.app to handle room closing upon timeout, using a scheduled task.  

Note:  There is no effective timeout in a DF.app session because our Visitor Abandonment takes precedence and is much shorter than any configured timeout in the DF.app. 

@bhardwajaditya can you please fix.  And don't forget 'searchable' in the custom-field POST

**Comment by bhardwajaditya** [comment]
@ear-dev these issues are fixed

**Comment by ear-dev** [comment]
All tests have passed.  We'll do a final lookover after we merge this into develop, and if it looks good we'll enable ECR push for this branch and deploy this into our dev environment.

**Pull request merged**
